[project]
name = "swimming-pool-diagram-generator"
version = "0.1.0"
description = "Generate vertical swimlane diagrams from a Mermaid-like DSL"
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = [
	"pillow>=10.4.0",
]

[project.scripts]
swimlane-gen = "swimlane_diagram_generator.cli:main"

[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["swimlane_diagram_generator"]

[tool.uv]
no-cache = true
prerelease = "if-necessary-or-explicit"
preview = true
upgrade = false

[tool.ruff]
preview = true

[tool.ruff.lint]
preview = true

[tool.ruff.format]
preview = true